include conf/distro/include/fsl-imx-base.inc
include conf/distro/include/fsl-imx-preferred-env.inc

DISTRO = "fsl-imx-base-elexot"

PREFERRED_PROVIDER_virtual/kernel:imx-nxp-bsp = "linux-elexot"
PREFERRED_PROVIDER_virtual/bootloader:imx-nxp-bsp = "u-boot-elexot"

IMAGE_FSTYPES += " wic.gz wic.sparse"
IMAGE_CLASSES += " image_types_sparse"
